### ISSUE TITLE
Visually distinguish custom payload fields from default payload fields

### ISSUE THREAD

**Issue by Jeehut** [TelemetryDeck/TelemetryViewer#130]
Currently when I provide custom payload fields to a signal, I find it hard to find my own payload data among all the default payload fields. As you can see, they are currently totally mixed together with the default payload fields (the blue ones are my custom fields):
![Screen Shot 2022-07-14 at 16 25 15](https://user-images.githubusercontent.com/6942160/179006482-88447ad8-e020-401f-9840-59b2285e2dbb.png)

I would suggest 2 things to improve the custom payload UX:
1. Somehow visually distinguish the custom fields from the default fields (e.g. by grouping, coloring, icon etc.)
2. Indicate on the signal list level already the signals that have custom fields attached (much like the Mail app signals attachments)

### Tasks
- [x] Do this in iOS and macOS
- [ ] Do this in the web dashboard
- [ ] Check if default payload strings from all SDKs are included.
